name: CI Pipeline
on: [push]
jobs:
  Compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Node Modules
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/node_modules  # Cache the backend's node_modules
          key: node-modules-${{ hashFiles('backend/package-lock.json') }}

      - name: Setup Node.js
        uses: actions/setup-node@v4  # Fixed action name (added "s")
        with:
          node-version: 20.x  # Updated to Node 20 (16.x is deprecated)
          cache: 'npm'

      - name: Install dependencies and build
        working-directory: ./backend
        run: |
          npm ci          # Clean install (uses package-lock.json)
          npm run build   # Build the project

      - name: Generate Artifact
        working-directory: ./backend/build
        run: |
          zip -r artifact.zip ./* -x '*.git*'  # Zip everything except .git files

      - name: Upload Artifact
        uses: actions/upload-artifact@v4  # Fixed action name and version
        with:
          name: backend-artifact
          path: backend/build/artifact.zip